import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header/Header";
import { ScreenResizeContextProvider } from "@/contexts/ScreenResize";
import Footer from "@/components/Footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "travel turkey",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <ScreenResizeContextProvider>
        <body className={inter.className}>
          <Header />
          {children}
          <Footer/>
        </body>
      </ScreenResizeContextProvider>
    </html>
  );
}
